name: Build Windows

permissions:
  contents: write

on:
  push:
    branches: [main, master]
  workflow_dispatch: # 允许手动触发

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build-windows:
    runs-on: windows-latest
    name: build Windows

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: dtolnay/rust-toolchain@stable

      - name: install Windows dependencies
        run: |
          vcpkg install dav1d:x64-windows
          echo "PKG_CONFIG_PATH=$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\pkgconfig" >> $env:GITHUB_ENV

      - name: install pnpm and dependencies
        run: |
          npm i pnpm -g
          pnpm i

      - name: build UI
        run: pnpm build:ui

      - name: build release
        run: cargo build --release

      - name: copy Windows DLLs
        run: |
          if (Test-Path "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin\dav1d.dll") {
            Copy-Item "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin\dav1d.dll" "target\release\"
          }
          # 复制其他可能需要的 DLLs
          Get-ChildItem "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin\*.dll" | ForEach-Object {
            Copy-Item $_.FullName "target\release\" -ErrorAction SilentlyContinue
          }

      - name: upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: |
            target/release/CzkawkaTauri.exe
            target/release/*.dll
